### ISSUE TITLE
No login page

### ISSUE THREAD

**Issue by darkwebduck** [SiriusScan/Sirius#2]
- Running `sudo docker-compose up -d`, no error in the logs
- http://ip:5173 is only showing the progress bar at 0% and a short message "you need to login" that disappear. This keeps the same for days.
- `sudo docker logs -f sirius_sirius-engine_1`
   watching .
watching core
watching core/scanners
watching lib
watching lib/nmap
!exclude tmp
building...
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/lair-framework/go-nmap v0.0.0-20191202052157-3507e0b03523
running...
Sirius Scanning Engine
2023/04/26 08:22:41 Failed to connect to RabbitMQ: dial tcp 172.18.0.2:5672: connect: connection refused
- `sudo docker inspect sirius_rabbitmq_1`
  "5672/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5672"
                    }
"Networks": {
                "sirius_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "rabbitmq",
                        "7c760390777b"
                    ],
                    "NetworkID": "5348d4d904490c517e500718c1ab8a7869063ad0039839e57e5438f2a678181e",
                    "EndpointID": "8066d706e7f85fc2eac3476ee4e94bd2242efa020213faf42cc39de849016a86",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2"

Any idea why it's stuck at 0%? Or why I don't get the login page?

**Comment by ppxv** [comment]
same problem

**Comment by EvanGrace25** [comment]
Encountering same issue. Not sure what to do to resolve.

**Comment by 0sm0s1z** [comment]
I think I see the issue here. It looks like the API is shutting down automatically because rabbitmq starts up more slowly than it and a connection refused message comes back. Adding a required line for it to the API part of the docker-compose file ought to fix that. I actually thought I'd already made that change...

I'll take a closer look and see what's going on.

**Comment by ghost** [comment]
I added these lines to the compose file and now everything is working fine. 
```
depends_on:
    rabbitmq:
       condition: service_healthy
```
Thanks for the help!

**Comment by EvanGrace25** [comment]
Added that depends_on condition to both API and engine, and it worked great. Thank you!

**Comment by spydisec** [comment]
I have updated as per the new docker-compose file, and made sure the API is connect to RabbitMQ. Still it shows 0% and cannot access the login page.  

As per the inspection from browser - It keep sending request to http://127.0.0.1:8080/api/status however, IP should be different.

**Comment by elguenny** [comment]
> I have updated as per the new docker-compose file, and made sure the API is connect to RabbitMQ. Still it shows 0% and cannot access the login page.
> 
> As per the inspection from browser - It keep sending request to http://127.0.0.1:8080/api/status however, IP should be different.

The problem is the config in UI/config.json

**Comment by kenvb** [comment]
> > I have updated as per the new docker-compose file, and made sure the API is connect to RabbitMQ. Still it shows 0% and cannot access the login page.
> > As per the inspection from browser - It keep sending request to http://127.0.0.1:8080/api/status however, IP should be different.
> 
> The problem is the config in UI/config.json

Can you elaborate on that please ? :)

**Comment by kenvb** [comment]
For those who are stuck on the 0% and don't see the login page (well technically it just appears for a split second). Just adapting the `./UI/config.json` file and using a hostname in stead of ip addresses seems to work out fine and is a quick fix.
